"""GitHub platform renderer test sub-package.

Re-exports all test functions for use by the top-level test runner, and
exposes GITHUB_PLATFORM_RENDERER_TESTS as the ordered list the runner appends
to _TESTS.
"""
from __future__ import annotations

from neutral_core_tests.github_platform_renderer_tests.test_workflow_structure import (
    test_privileged_stage_produces_pull_request_target,
    test_non_privileged_stage_renders_successfully,
    test_pr_opened_trigger_maps_to_pull_request_target_opened_events,
    test_pr_updated_trigger_maps_to_pull_request_target_synchronize,
    test_manual_trigger_maps_to_workflow_dispatch,
    test_issue_labeled_trigger_maps_to_issues_labeled,
    test_workflow_contains_concurrency_block,
    test_concurrency_cancel_in_progress_is_false,
    test_concurrency_key_includes_stage_id,
    test_concurrency_key_includes_pr_number_expression,
    test_concurrency_key_includes_issue_number_fallback,
    test_first_step_references_private_key_secret,
    test_first_step_references_publisher_app_id,
    test_app_token_step_has_id_app_token,
    test_backend_invocation_step_uses_trusted_commenter_token,
    test_backend_invocation_step_does_not_use_app_token,
    test_result_signaling_step_uses_app_token,
    test_workflow_file_written_with_correct_name,
    test_backend_invocation_step_env_is_plan_driven,
    test_backend_invocation_step_has_no_env_when_plan_has_no_secrets,
    test_app_token_action_uses_pinned_sha,
)
from neutral_core_tests.github_platform_renderer_tests.test_result_spec import (
    test_render_stage_returns_stage_result_spec,
    test_stage_result_spec_signal_kind_is_check_run,
    test_stage_result_spec_provenance_publisher_identity_equals_app_id,
    test_stage_result_spec_signal_selector_contains_stage_id,
    test_stage_result_spec_stage_id_matches_stage,
    test_dry_run_render_stage_returns_stage_result_spec,
    test_dry_run_produces_no_files,
    test_dry_run_produces_no_files_positive_control,
    test_dry_run_render_routing_raises_value_error,
    test_live_mode_render_routing_writes_workflow_file,
    test_dry_run_render_governance_raises_value_error,
    test_live_mode_render_governance_raises_not_implemented_error,
    test_github_platform_renderer_protocol_conformance,
    test_pr_opened_and_pr_updated_combine_into_single_pull_request_target_block,
    test_manual_trigger_produces_workflow_dispatch_only,
)
from neutral_core_tests.github_platform_renderer_tests.test_routing_workflow import (
    test_fast_path_null_produces_normal_immediately,
    test_all_paths_match_classifies_as_fast,
    test_any_path_mismatch_classifies_as_normal,
    test_routing_workflow_first_step_references_private_key_secret,
    test_fast_path_configured_workflow_embeds_patterns_as_json_constant,
)

GITHUB_PLATFORM_RENDERER_TESTS = [
    test_privileged_stage_produces_pull_request_target,
    test_non_privileged_stage_renders_successfully,
    test_pr_opened_trigger_maps_to_pull_request_target_opened_events,
    test_pr_updated_trigger_maps_to_pull_request_target_synchronize,
    test_manual_trigger_maps_to_workflow_dispatch,
    test_issue_labeled_trigger_maps_to_issues_labeled,
    test_workflow_contains_concurrency_block,
    test_concurrency_cancel_in_progress_is_false,
    test_concurrency_key_includes_stage_id,
    test_concurrency_key_includes_pr_number_expression,
    test_concurrency_key_includes_issue_number_fallback,
    test_first_step_references_private_key_secret,
    test_first_step_references_publisher_app_id,
    test_app_token_step_has_id_app_token,
    test_backend_invocation_step_uses_trusted_commenter_token,
    test_backend_invocation_step_does_not_use_app_token,
    test_result_signaling_step_uses_app_token,
    test_workflow_file_written_with_correct_name,
    test_backend_invocation_step_env_is_plan_driven,
    test_backend_invocation_step_has_no_env_when_plan_has_no_secrets,
    test_app_token_action_uses_pinned_sha,
    test_render_stage_returns_stage_result_spec,
    test_stage_result_spec_signal_kind_is_check_run,
    test_stage_result_spec_provenance_publisher_identity_equals_app_id,
    test_stage_result_spec_signal_selector_contains_stage_id,
    test_stage_result_spec_stage_id_matches_stage,
    test_dry_run_render_stage_returns_stage_result_spec,
    test_dry_run_produces_no_files,
    test_dry_run_produces_no_files_positive_control,
    test_dry_run_render_routing_raises_value_error,
    test_live_mode_render_routing_writes_workflow_file,
    test_dry_run_render_governance_raises_value_error,
    test_live_mode_render_governance_raises_not_implemented_error,
    test_github_platform_renderer_protocol_conformance,
    test_pr_opened_and_pr_updated_combine_into_single_pull_request_target_block,
    test_manual_trigger_produces_workflow_dispatch_only,
    test_fast_path_null_produces_normal_immediately,
    test_all_paths_match_classifies_as_fast,
    test_any_path_mismatch_classifies_as_normal,
    test_routing_workflow_first_step_references_private_key_secret,
    test_fast_path_configured_workflow_embeds_patterns_as_json_constant,
]

__all__ = [
    "GITHUB_PLATFORM_RENDERER_TESTS",
    "test_privileged_stage_produces_pull_request_target",
    "test_non_privileged_stage_renders_successfully",
    "test_pr_opened_trigger_maps_to_pull_request_target_opened_events",
    "test_pr_updated_trigger_maps_to_pull_request_target_synchronize",
    "test_manual_trigger_maps_to_workflow_dispatch",
    "test_issue_labeled_trigger_maps_to_issues_labeled",
    "test_workflow_contains_concurrency_block",
    "test_concurrency_cancel_in_progress_is_false",
    "test_concurrency_key_includes_stage_id",
    "test_concurrency_key_includes_pr_number_expression",
    "test_concurrency_key_includes_issue_number_fallback",
    "test_first_step_references_private_key_secret",
    "test_first_step_references_publisher_app_id",
    "test_app_token_step_has_id_app_token",
    "test_backend_invocation_step_uses_trusted_commenter_token",
    "test_backend_invocation_step_does_not_use_app_token",
    "test_result_signaling_step_uses_app_token",
    "test_workflow_file_written_with_correct_name",
    "test_backend_invocation_step_env_is_plan_driven",
    "test_backend_invocation_step_has_no_env_when_plan_has_no_secrets",
    "test_app_token_action_uses_pinned_sha",
    "test_render_stage_returns_stage_result_spec",
    "test_stage_result_spec_signal_kind_is_check_run",
    "test_stage_result_spec_provenance_publisher_identity_equals_app_id",
    "test_stage_result_spec_signal_selector_contains_stage_id",
    "test_stage_result_spec_stage_id_matches_stage",
    "test_dry_run_render_stage_returns_stage_result_spec",
    "test_dry_run_produces_no_files",
    "test_dry_run_produces_no_files_positive_control",
    "test_dry_run_render_routing_raises_value_error",
    "test_live_mode_render_routing_writes_workflow_file",
    "test_dry_run_render_governance_raises_value_error",
    "test_live_mode_render_governance_raises_not_implemented_error",
    "test_github_platform_renderer_protocol_conformance",
    "test_pr_opened_and_pr_updated_combine_into_single_pull_request_target_block",
    "test_manual_trigger_produces_workflow_dispatch_only",
    "test_fast_path_null_produces_normal_immediately",
    "test_all_paths_match_classifies_as_fast",
    "test_any_path_mismatch_classifies_as_normal",
    "test_routing_workflow_first_step_references_private_key_secret",
    "test_fast_path_configured_workflow_embeds_patterns_as_json_constant",
]
