"""Non-interactive template rendering — `generate` a commented `.agentic/config.yml` from choices."""
from __future__ import annotations

import json
from typing import Any

from .detect import CUSTOM_PRESET, _BUILD_PRESET_OPTIONS
from .defaults import PROFILES, _DOCS_CONFIG, default_choices
from .snippets import _stages_block


def generate(choices: dict[str, Any]) -> str:
    """Render a commented `.agentic/config.yml` from the collected choices."""
    profile = choices.get("profile")
    if profile not in PROFILES:
        raise ValueError(f"unknown profile '{profile}'; choose one of: {', '.join(PROFILES)}")
    resolved = {**default_choices(profile), **choices}

    test_cmd = resolved["build_test"]
    if test_cmd:
        test_hint = ""
    elif resolved["build_preset"] != CUSTOM_PRESET:
        # An empty override inherits the preset's test command at render time (render._build_steps).
        test_hint = f"            # blank inherits the {resolved['build_preset']} preset's test; set to override"
    else:
        test_hint = '            # e.g. "pytest" / "npm test" — no preset default; set your test command'
    stages_block = _stages_block(resolved)
    # Emit every free-form string as a JSON scalar (a valid YAML double-quoted scalar), so a value
    # that YAML would otherwise reinterpret — a branch named `on`/`no` (bool), a name with a colon
    # or quote — round-trips as the intended string instead of failing `stagr doctor`.
    branch = json.dumps(resolved["default_branch"])
    token_secret = json.dumps(resolved["token_secret"])
    model = json.dumps(resolved["model"])

    return f"""\
# .agentic/config.yml — generated by `stagr init` (profile: {profile}).
# One declarative file; `stagr apply` renders it into .github/workflows/. Trim or extend freely.
# Validate and preview with `stagr doctor` then `stagr plan`.
# Full reference: {_DOCS_CONFIG}
version: 2
profile: custom                 # stages are listed explicitly below

platform:
  type: {resolved['platform']}                  # only 'github' renders today; other platforms are roadmap
  default_branch: {branch}
  # NAME of the real-user PAT that pushes the implementer's validated fixes / re-requests reviews,
  # kept separate from the untrusted implementer's own credentials. Value lives in CI secrets.
  auth: {{ token_secret: {token_secret} }}

defaults:
  # Provider is the knob; the tool is derived (anthropic -> Claude Code, openai -> Codex).
  provider: anthropic
  models:
    # Model the Claude implementer uses. Change to your provider's model id.
    anthropic: {{ default: {model} }}

build:
  # What "green" means for THIS repo — your own checks. Omit the whole block for a docs-only repo.
  preset: {resolved['build_preset']}                # {_BUILD_PRESET_OPTIONS}
  commands:
    test: {json.dumps(test_cmd)}{test_hint}

{stages_block}

# Optional blocks (delete any to accept its default):
#   routing.fast_path      — skip paid review for trivial docs/text changes
#   modules.auto_merge     — render the fail-closed auto-merge gate (default off = humans merge)
#   merge.required_status_checks — external checks (Sonar/Checkmarx/…) the gate requires, by name
#   budgets                — cap cost/tokens per run
#   skills:                — register your own review/security skills (source: path), bind via stages[].skill
# See {_DOCS_CONFIG} for the full, annotated surface.
"""
